services:
  postgres-test:
    image: postgres:16-alpine
    container_name: postgres-test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]

  backend-test:
    container_name: backend-test
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - ./backend:/app/backend
      - ./tests:/app/tests
    depends_on:
      postgres-test:
        condition: service_healthy