services:
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: dev
    volumes:
      - ./backend:/app/backend
      - ./migrations:/app/migrations
      - ./.env:/app/.env
    environment:
      - ENV=development
      - PYTHONUNBUFFERED=1
      # - PYTHONPATH=/app

    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
