"""enums

Revision ID: 34faa725ce27
Revises: a8ae60e6c4c5
Create Date: 2025-12-27 12:44:59.698582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34faa725ce27'
down_revision: Union[str, None] = 'a8ae60e6c4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='orgstatusenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
