"""extended

Revision ID: 52dfbeeff3dc
Revises: 79589f7951e9
Create Date: 2025-12-22 16:44:16.961636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '52dfbeeff3dc'
down_revision: Union[str, None] = '79589f7951e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('organizations', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('organizations', sa.Column('adress', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('organizations', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('organizations', sa.Column('social_links', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('organizations', sa.Column('charter_file', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'charter_file')
    op.drop_column('organizations', 'social_links')
    op.drop_column('organizations', 'phone_number')
    op.drop_column('organizations', 'adress')
    op.drop_column('organizations', 'region')
    op.drop_column('organizations', 'short_name')
    # ### end Alembic commands ###
