"""added cascade deleting

Revision ID: 62cf2ccf5f71
Revises: 9c03c4f9a3a0
Create Date: 2025-05-23 16:05:41.166059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62cf2ccf5f71'
down_revision: Union[str, None] = '9c03c4f9a3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exhibition_block_items_block_id_fkey', 'exhibition_block_items', type_='foreignkey')
    op.create_foreign_key(None, 'exhibition_block_items', 'exhibition_blocks', ['block_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('exhibition_blocks_exhibition_id_fkey', 'exhibition_blocks', type_='foreignkey')
    op.create_foreign_key(None, 'exhibition_blocks', 'exhibitions', ['exhibition_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('exhibition_exhibits_exhibition_id_fkey', 'exhibition_exhibits', type_='foreignkey')
    op.drop_constraint('exhibition_exhibits_exhibit_id_fkey', 'exhibition_exhibits', type_='foreignkey')
    op.create_foreign_key(None, 'exhibition_exhibits', 'exhibits', ['exhibit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exhibition_exhibits', 'exhibitions', ['exhibition_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('exhibition_participants_exhibition_id_fkey', 'exhibition_participants', type_='foreignkey')
    op.create_foreign_key(None, 'exhibition_participants', 'exhibitions', ['exhibition_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('exhibition_tags_tag_id_fkey', 'exhibition_tags', type_='foreignkey')
    op.drop_constraint('exhibition_tags_exhibition_id_fkey', 'exhibition_tags', type_='foreignkey')
    op.create_foreign_key(None, 'exhibition_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exhibition_tags', 'exhibitions', ['exhibition_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exhibition_tags', type_='foreignkey')
    op.drop_constraint(None, 'exhibition_tags', type_='foreignkey')
    op.create_foreign_key('exhibition_tags_exhibition_id_fkey', 'exhibition_tags', 'exhibitions', ['exhibition_id'], ['id'])
    op.create_foreign_key('exhibition_tags_tag_id_fkey', 'exhibition_tags', 'tags', ['tag_id'], ['id'])
    op.drop_constraint(None, 'exhibition_participants', type_='foreignkey')
    op.create_foreign_key('exhibition_participants_exhibition_id_fkey', 'exhibition_participants', 'exhibitions', ['exhibition_id'], ['id'])
    op.drop_constraint(None, 'exhibition_exhibits', type_='foreignkey')
    op.drop_constraint(None, 'exhibition_exhibits', type_='foreignkey')
    op.create_foreign_key('exhibition_exhibits_exhibit_id_fkey', 'exhibition_exhibits', 'exhibits', ['exhibit_id'], ['id'])
    op.create_foreign_key('exhibition_exhibits_exhibition_id_fkey', 'exhibition_exhibits', 'exhibitions', ['exhibition_id'], ['id'])
    op.drop_constraint(None, 'exhibition_blocks', type_='foreignkey')
    op.create_foreign_key('exhibition_blocks_exhibition_id_fkey', 'exhibition_blocks', 'exhibitions', ['exhibition_id'], ['id'])
    op.drop_constraint(None, 'exhibition_block_items', type_='foreignkey')
    op.create_foreign_key('exhibition_block_items_block_id_fkey', 'exhibition_block_items', 'exhibition_blocks', ['block_id'], ['id'])
    # ### end Alembic commands ###
