"""user

Revision ID: 65aeeef29682
Revises: f8d94bc05f1d
Create Date: 2026-01-11 18:16:45.456822

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "65aeeef29682"
down_revision: Union[str, None] = "f8d94bc05f1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admin_actions",
        "action_type",
        existing_type=postgresql.ENUM(
            "approve_org", "block_user", "unblock_user", "reset_password", name="actiontypeenum"
        ),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "exhibition_blocks",
        "type",
        existing_type=postgresql.ENUM(
            "HEADER",
            "TEXT",
            "QUOTE",
            "IMAGE_TEXT_RIGHT",
            "IMAGE_TEXT_LEFT",
            "LAYOUT_IMG_TEXT_IMG",
            "LAYOUT_TEXT_IMG_TEXT",
            "IMAGES_2",
            "IMAGES_3",
            "IMAGES_4",
            "CAROUSEL",
            name="exhibitionblocktypeenum",
        ),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        server_default=None,
        existing_nullable=True,
    )
    op.add_column(
        "users_organizations",
        sa.Column(
            "role", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="member"
        ),
    )
    op.drop_column("users_organizations", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_organizations",
        sa.Column(
            "status",
            postgresql.ENUM("active", "left", name="userorganizationenum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users_organizations", "role")
    op.alter_column(
        "exhibition_blocks",
        "type",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=postgresql.ENUM(
            "HEADER",
            "TEXT",
            "QUOTE",
            "IMAGE_TEXT_RIGHT",
            "IMAGE_TEXT_LEFT",
            "LAYOUT_IMG_TEXT_IMG",
            "LAYOUT_TEXT_IMG_TEXT",
            "IMAGES_2",
            "IMAGES_3",
            "IMAGES_4",
            "CAROUSEL",
            name="exhibitionblocktypeenum",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "admin_actions",
        "action_type",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=postgresql.ENUM(
            "approve_org", "block_user", "unblock_user", "reset_password", name="actiontypeenum"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
