"""added

Revision ID: 79589f7951e9
Revises: d3185d60b8f7
Create Date: 2025-12-02 16:38:31.395265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79589f7951e9'
down_revision: Union[str, None] = 'd3185d60b8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exhibitions', 'start_year')
    op.drop_column('exhibitions', 'end_year')
    op.drop_column('exhibitions', 'date_template')
    op.add_column('exhibits', sa.Column('date_template', sa.Enum('year', 'decade', 'century', name='datetemplate'), nullable=True))
    op.add_column('exhibits', sa.Column('start_year', sa.Integer(), nullable=True))
    op.add_column('exhibits', sa.Column('end_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exhibits', 'end_year')
    op.drop_column('exhibits', 'start_year')
    op.drop_column('exhibits', 'date_template')
    op.add_column('exhibitions', sa.Column('date_template', postgresql.ENUM('year', 'decade', 'century', name='datetemplate'), autoincrement=False, nullable=True))
    op.add_column('exhibitions', sa.Column('end_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exhibitions', sa.Column('start_year', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
