"""nullable organization id in exhibition

Revision ID: 9c03c4f9a3a0
Revises: b932cfca0a55
Create Date: 2025-05-22 14:35:17.229857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c03c4f9a3a0'
down_revision: Union[str, None] = 'b932cfca0a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exhibitions', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exhibitions', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
