"""head_info

Revision ID: b1a18e471f70
Revises: baa595b72034
Create Date: 2026-01-12 15:19:42.431170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b1a18e471f70'
down_revision: Union[str, None] = 'baa595b72034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('head_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('organizations', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('organizations', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('organizations', 'adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('adress', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'head_info')
    # ### end Alembic commands ###
