"""adminaction

Revision ID: b331a642555f
Revises: 65aeeef29682
Create Date: 2026-01-11 18:44:58.695236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b331a642555f'
down_revision: Union[str, None] = '65aeeef29682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_actions', sa.Column('target_exhibition_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'admin_actions', 'exhibitions', ['target_exhibition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_actions', type_='foreignkey')
    op.drop_column('admin_actions', 'target_exhibition_id')
    # ### end Alembic commands ###
