"""try to migrate some tables v3

Revision ID: b932cfca0a55
Revises: 7df14b64db41
Create Date: 2025-05-21 16:45:41.300491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b932cfca0a55'
down_revision: Union[str, None] = '7df14b64db41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exhibition_block_items',
    sa.Column('image_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['exhibition_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('templates', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('exhibition_block_items')
    # ### end Alembic commands ###
