"""created_at

Revision ID: baa595b72034
Revises: b331a642555f
Create Date: 2026-01-12 01:50:55.849816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa595b72034'
down_revision: Union[str, None] = 'b331a642555f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exhibition_moderation_comments', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('organization_moderation_comments', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_moderation_comments', 'created_at')
    op.drop_column('exhibition_moderation_comments', 'created_at')
    # ### end Alembic commands ###
