"""added date template

Revision ID: d3185d60b8f7
Revises: a8ef598bc4ac
Create Date: 2025-11-15 15:09:47.857275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3185d60b8f7'
down_revision: Union[str, None] = 'a8ef598bc4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    date_template = sa.Enum('year', "decade", "century", name='datetemplate')
    # create enum type in the DB before adding the column (Postgres requires it)
    date_template.create(op.get_bind(), checkfirst=True)
    op.add_column('exhibitions', sa.Column(
        'date_template', date_template, nullable=True))
    op.add_column('exhibitions', sa.Column(
        'start_year', sa.Integer(), nullable=True))
    op.add_column('exhibitions', sa.Column(
        'end_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exhibitions', 'end_year')
    op.drop_column('exhibitions', 'start_year')
    op.drop_column('exhibitions', 'date_template')
    # drop enum type
    date_template = sa.Enum('year', "decade", "century", name='datetemplate')
    date_template.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
