"""image_url -> image_key

Revision ID: d4666b150d41
Revises: 1200944195d9
Create Date: 2025-04-30 15:32:17.070509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd4666b150d41'
down_revision: Union[str, None] = '1200944195d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exhibits', sa.Column('image_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_column('exhibits', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exhibits', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('exhibits', 'image_key')
    # ### end Alembic commands ###
