"""enums

Revision ID: dd61201ec752
Revises: 34faa725ce27
Create Date: 2025-12-27 12:45:36.724676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd61201ec752"
down_revision: Union[str, None] = "34faa725ce27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    org_status_enum = sa.Enum(
        "approved", "draft", "on_moderation", "needs_revision", name="orgstatusenum"
    )
    org_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "organizations",
        sa.Column("status", org_status_enum, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "status")
    sa.Enum(name="orgstatusenum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
