"""enums

Revision ID: f8d94bc05f1d
Revises: dd61201ec752
Create Date: 2025-12-27 14:57:55.899780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f8d94bc05f1d'
down_revision: Union[str, None] = 'dd61201ec752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exhibitions', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'archived', name='exhibitionstatusenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('organizations', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='orgstatusenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='orgstatusenum'),
               existing_nullable=True)
    op.alter_column('exhibitions', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('draft', 'published', 'archived', name='exhibitionstatusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
