"""added description in exhibition table

Revision ID: fe90f92ba392
Revises: 62cf2ccf5f71
Create Date: 2025-05-23 18:39:50.214131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe90f92ba392'
down_revision: Union[str, None] = '62cf2ccf5f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exhibitions', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exhibitions', 'description')
    # ### end Alembic commands ###
